-- MySQL Script generated by MySQL Workbench
-- Mon Oct 31 10:46:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cleanier
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cleanier
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cleanier` DEFAULT CHARACTER SET utf8 ;
USE `db_cleanier` ;

-- -----------------------------------------------------
-- Table `db_cleanier`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cleanier`.`user` (
  `id` INT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NOT NULL,
  `delivery address` VARCHAR(45) NOT NULL,
  `phone_number` INT NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `card_number` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `e-mail_UNIQUE` (`e_mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cleanier`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cleanier`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cleanier`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cleanier`.`product` (
  `id` INT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `capacity` VARCHAR(45) NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `category_category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_product_category1_idx` (`category_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_category_id`)
    REFERENCES `db_cleanier`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cleanier`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cleanier`.`order` (
  `id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `total_price` INT NOT NULL,
  `order_date` DATE NOT NULL,
  `product_id` INT NOT NULL,
  `order_status` VARCHAR(45) NOT NULL,
  `shipping_date` DATE NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`) = 0
    REFERENCES `db_cleanier`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cleanier`.`order_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cleanier`.`order_has_product` (
  `order_id` INT NOT NULL,
  `product_product_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `product_product_id`),
  INDEX `fk_order_has_product_product1_idx` (`product_product_id` ASC) VISIBLE,
  INDEX `fk_order_has_product_order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_has_product_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `db_cleanier`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_product_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `db_cleanier`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `db_cleanier` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `db_cleanier`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
